/* ============================================================================
   Deepwater service worker.

   Cache-first for everything. The requirement (spec §3.1) is that the game
   loads and plays with the network completely disabled on the first launch
   after install — so the install step must precache every module, not just
   the shell. The PRECACHE list between the BEGIN/END markers is generated by
   `node tools/gen-precache.mjs`; don't hand-edit it, it will be overwritten.
   ========================================================================= */

const VERSION = 'deepwater-v1';
const CACHE = `${VERSION}`;

/* ---- PRECACHE:BEGIN (generated — do not edit by hand) ---- */
const PRECACHE = [
  './',
  './assets/art/index.json',
  './assets/atlas.json',
  './assets/atlas.png',
  './assets/fonts/IBMPlexMono-Regular.woff2',
  './assets/fonts/IBMPlexSans-Medium.woff2',
  './assets/fonts/IBMPlexSans-Regular.woff2',
  './assets/fonts/SairaCondensed-SemiBold.woff2',
  './assets/icon-192.png',
  './assets/icon-512.png',
  './assets/icon-maskable-512.png',
  './index.html',
  './manifest.webmanifest',
  './src/audio/audio.js',
  './src/config/balance.js',
  './src/core/catchup.js',
  './src/core/events.js',
  './src/core/game.js',
  './src/core/loop.js',
  './src/core/migrations.js',
  './src/core/newgame.js',
  './src/core/reducers.js',
  './src/core/rng.js',
  './src/core/save.js',
  './src/core/store.js',
  './src/data/artwork.js',
  './src/data/briefing.js',
  './src/data/encounters.js',
  './src/data/events.js',
  './src/data/items.js',
  './src/data/levels.js',
  './src/data/names.js',
  './src/data/policies.js',
  './src/data/research.js',
  './src/data/rooms.js',
  './src/data/silos.js',
  './src/data/traits.js',
  './src/data/tutorial.js',
  './src/main.js',
  './src/render/canvas.js',
  './src/render/citizens.js',
  './src/render/depthgauge.js',
  './src/render/floors.js',
  './src/render/portraits.js',
  './src/render/sprites.js',
  './src/sim/build.js',
  './src/sim/combat.js',
  './src/sim/dig.js',
  './src/sim/diplomacy.js',
  './src/sim/directives.js',
  './src/sim/economy.js',
  './src/sim/events.js',
  './src/sim/expedition.js',
  './src/sim/jobs.js',
  './src/sim/military.js',
  './src/sim/order.js',
  './src/sim/population.js',
  './src/sim/research.js',
  './src/sim/unlocks.js',
  './src/sim/world.js',
  './src/ui/artwork.js',
  './src/ui/briefing.js',
  './src/ui/citizenCard.js',
  './src/ui/dom.js',
  './src/ui/ending.js',
  './src/ui/panels/airlock.js',
  './src/ui/panels/build.js',
  './src/ui/panels/log.js',
  './src/ui/panels/military.js',
  './src/ui/panels/policy.js',
  './src/ui/panels/population.js',
  './src/ui/panels/radio.js',
  './src/ui/panels/research.js',
  './src/ui/panels/resources.js',
  './src/ui/returnReport.js',
  './src/ui/roomView.js',
  './src/ui/settings.js',
  './src/ui/shell.js',
  './src/ui/styles.css',
  './src/ui/tutorial.css',
  './src/ui/tutorial.js',
];
/* ---- PRECACHE:END ---- */

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // addAll is atomic-ish but fails the whole install on one 404. During
      // development a missing optional asset shouldn't brick the worker, so
      // we add individually and tolerate misses.
      await Promise.all(
        PRECACHE.map(async (url) => {
          try {
            const res = await fetch(url, { cache: 'reload' });
            if (res.ok) await cache.put(url, res);
          } catch (_) {
            /* optional asset absent — fine */
          }
        })
      );
      await self.skipWaiting();
    })()
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
      await self.clients.claim();
    })()
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // never touch cross-origin

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      const hit = await cache.match(req, { ignoreSearch: true });
      if (hit) {
        // Cache-first, but quietly refresh in the background when online so
        // an updated build lands on the next launch.
        revalidate(cache, req);
        return hit;
      }
      try {
        const res = await fetch(req);
        if (res && res.ok && res.type === 'basic') cache.put(req, res.clone());
        return res;
      } catch (err) {
        // Navigation offline with nothing cached for this exact URL: fall
        // back to the app shell so a deep link still boots the game.
        if (req.mode === 'navigate') {
          const shell = await cache.match('./index.html');
          if (shell) return shell;
        }
        return new Response('Offline and not cached.', {
          status: 503,
          headers: { 'Content-Type': 'text/plain' },
        });
      }
    })()
  );
});

function revalidate(cache, req) {
  fetch(req)
    .then((res) => {
      if (res && res.ok && res.type === 'basic') cache.put(req, res.clone());
    })
    .catch(() => {});
}

self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting();
  if (event.data === 'VERSION') {
    event.source?.postMessage({ type: 'VERSION', version: VERSION });
  }
});
