/**
 * sprites.js — atlas loader and animation state machines.
 *
 * The atlas is generated by tools/gen-atlas.mjs, so it is on-palette by
 * construction. If it fails to load the renderer falls back to the procedural
 * block shapes it used before Phase 8 — the game must never fail to draw
 * because an image 404'd.
 */

import { BAL } from '../config/balance.js';

let atlas = null;
let table = null;
let loading = null;
let failed = false;

export function isLoaded() {
  return !!atlas && !!table;
}

export function hasFailed() {
  return failed;
}

/** Load the atlas image and its frame table. Resolves either way. */
export async function loadAtlas(base = './assets/') {
  if (atlas && table) return true;
  if (loading) return loading;

  loading = (async () => {
    try {
      const [img, json] = await Promise.all([
        loadImage(base + 'atlas.png'),
        fetch(base + 'atlas.json').then((r) => r.json()),
      ]);
      atlas = img;
      table = json;
      return true;
    } catch (err) {
      console.warn('[sprites] atlas unavailable, falling back to block shapes:', err);
      failed = true;
      return false;
    }
  })();
  return loading;
}

function loadImage(src) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error('image failed: ' + src));
    img.src = src;
  });
}

export function frame(name) {
  return table?.frames?.[name] || null;
}

/**
 * Draw a frame, stretched to fit a destination box. Nearest-neighbour is
 * enforced by the caller setting imageSmoothingEnabled = false.
 */
export function draw(ctx, name, dx, dy, dw, dh) {
  if (!atlas || !table) return false;
  const f = table.frames[name];
  if (!f) return false;
  ctx.drawImage(atlas, f.x, f.y, f.w, f.h, dx, dy, dw ?? f.w, dh ?? f.h);
  return true;
}

/** Draw a frame at its natural size, top-left anchored. */
export function drawAt(ctx, name, dx, dy, scale = 1) {
  const f = frame(name);
  if (!f) return false;
  return draw(ctx, name, dx, dy, f.w * scale, f.h * scale);
}

// ------------------------------------------------------- animation state ---

/**
 * Citizen animation is derived, never stored: the frame is a pure function of
 * (id, time, state). That keeps it out of the save file and free during
 * catch-up, and it means a citizen's gait is stable across sessions.
 */
export function citizenFrame(citizen, timeMs, moving) {
  const palette = citizenPalette(citizen);
  if (!moving) {
    const f = Math.floor(timeMs / 420 + citizen.id) % 2;
    return `citizen_${palette}_work${f}`;
  }
  const f = Math.floor(timeMs / 150 + citizen.id * 3) % 4;
  return `citizen_${palette}_walk${f}`;
}

export function citizenPalette(c) {
  if (c.radiation >= BAL.citizens.radiation.sicknessThreshold) return 'irradiated';
  if (c.health < 45) return 'hurt';
  if (c.age < BAL.citizens.workingAgeMin) return 'child';
  if (c.status === 'idle') return 'idle';
  return 'worker';
}

/** In-world numerals, from the baked 3x5 font. UI text never goes on canvas. */
export function drawNumber(ctx, n, x, y, scale = 1) {
  const s = String(Math.max(0, Math.floor(n)));
  let cx = x;
  for (const ch of s) {
    const f = frame(`digit_${ch}`);
    if (!f) return false;
    draw(ctx, `digit_${ch}`, cx, y, f.w * scale, f.h * scale);
    cx += (f.w + 1) * scale;
  }
  return true;
}

export function numberWidth(n, scale = 1) {
  return String(Math.max(0, Math.floor(n))).length * 4 * scale;
}

export default { loadAtlas, draw, drawAt, frame, citizenFrame, drawNumber, isLoaded };
