/**
 * sprites.js — atlas loader and animation state machines.
 *
 * The atlas is generated by tools/gen-atlas.mjs, so it is on-palette by
 * construction. If it fails to load the renderer falls back to the procedural
 * block shapes it used before Phase 8 — the game must never fail to draw
 * because an image 404'd.
 */

import { BAL } from '../config/balance.js';

let atlas = null;
let table = null;
let loading = null;
let failed = false;

export function isLoaded() {
  return !!atlas && !!table;
}

export function hasFailed() {
  return failed;
}

/** Load the atlas image and its frame table. Resolves either way. */
export async function loadAtlas(base = './assets/') {
  if (atlas && table) return true;
  if (loading) return loading;

  loading = (async () => {
    try {
      const [img, json] = await Promise.all([
        loadImage(base + 'atlas.png'),
        fetch(base + 'atlas.json').then((r) => r.json()),
      ]);
      if (!adoptAtlas(img, json)) throw new Error('atlas.json carried no frame table');
      return true;
    } catch (err) {
      console.warn('[sprites] atlas unavailable, falling back to block shapes:', err);
      failed = true;
      return false;
    }
  })();
  return loading;
}

/**
 * Install an atlas that is already decoded. `loadAtlas` fetches one; this
 * takes one.
 *
 * It is here because the branch the player actually sees was covered by
 * nothing. `drawAt` returns false before it looks at its arguments when no
 * atlas is loaded, and `loadAtlas` needs `Image` and `fetch`, so under node
 * every assertion in the suite went through the procedural fallback in
 * citizens.js — the sprite anchors could be moved two hundred pixels with the
 * whole suite green. test/atlas.mjs adopts the real assets/atlas.json through
 * here and checks where the frames land.
 *
 * The frame-table check is not only for tests. This module's contract is that
 * the game never stops drawing because an asset went missing, and JSON that
 * parses but is not an atlas — a stale manifest, the wrong file resolved under
 * a subpath — used to install itself and then make every later draw throw on
 * `table.frames[name]`, which is a worse failure than the fallback it was
 * meant to avoid.
 */
export function adoptAtlas(image, frameTable) {
  if (!image || !frameTable?.frames) return false;
  atlas = image;
  table = frameTable;
  failed = false;
  return true;
}

function loadImage(src) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error('image failed: ' + src));
    img.src = src;
  });
}

export function frame(name) {
  return table?.frames?.[name] || null;
}

/**
 * Which tones in a role's baked portrait are that person's colouring.
 *
 * The sheet carries eleven portraits and the silo carries six hundred people,
 * so the card and the roster were showing one of eleven faces to everybody who
 * held the same job — and, worse, disagreeing with each other, because the
 * lists drew the per-citizen procedural portrait and the card drew the baked
 * one. Tapping a row changed a person's face.
 *
 * gen-atlas.mjs emits this from the art library's own provenance map: the skin
 * and hair tones the baker actually mixed, each with the shade() step that
 * separates it from its family's base. See `faceTones` there. Absent — an
 * older atlas, or no atlas at all — every caller falls back to what it drew
 * before, which is why this returns null rather than a default.
 */
export function faceTones(role) {
  return table?.faces?.[role] || null;
}

/**
 * Draw a frame, stretched to fit a destination box. Nearest-neighbour is
 * enforced by the caller setting imageSmoothingEnabled = false.
 */
export function draw(ctx, name, dx, dy, dw, dh) {
  if (!atlas || !table) return false;
  const f = table.frames[name];
  if (!f) return false;
  ctx.drawImage(atlas, f.x, f.y, f.w, f.h, dx, dy, dw ?? f.w, dh ?? f.h);
  return true;
}

/** Draw a frame at its natural size, top-left anchored. */
export function drawAt(ctx, name, dx, dy, scale = 1) {
  const f = frame(name);
  if (!f) return false;
  return draw(ctx, name, dx, dy, f.w * scale, f.h * scale);
}

// ------------------------------------------------------- animation state ---

/**
 * Citizen animation is derived, never stored: the frame is a pure function of
 * (id, time, state). That keeps it out of the save file and free during
 * catch-up, and it means a citizen's gait is stable across sessions.
 */
export function citizenFrame(citizen, timeMs, action) {
  const role = citizenRole(citizen);
  const act = FRAME_COUNTS[action] ? action : 'idle';
  const n = FRAME_COUNTS[act];
  // Phase by id so two people on the same floor are never in lockstep.
  const f = Math.floor(timeMs / FRAME_MS[act] + citizen.id * 3) % n;
  return `citizen_${role}_${act}${f}`;
}

/**
 * Frames per action, matching what tools/art/citizens.mjs bakes.
 *
 * "Matching" is now checked rather than asserted in prose: test/atlas.mjs
 * walks every name `citizenFrame` can produce and fails on any the sheet does
 * not carry, and on any citizen frame in the sheet that nothing can name. It
 * found a `die: 4` here that the baker had stopped baking — 44 frames this
 * table named and the atlas did not have. The only thing that could ask for
 * them was a `citizenFrameOnce` helper with no callers, left behind when the
 * death animation became the tappable skull marker `drawCitizens` draws now.
 * Both are gone: a citizen dying is a mark on the floor, not a collapse.
 */
const FRAME_COUNTS = { walk: 6, idle: 4, work: 4, sleep: 2, injured: 4, talk: 4, fight: 4 };
/**
 * How long each frame holds. Sleep breathes slowly; a walk cycle does not.
 *
 * A fight is the fastest thing on the screen because it is the only animation
 * that is meant to look urgent, and a conversation is the slowest of the
 * standing set because people gesture at about half the rate they walk.
 */
const FRAME_MS = {
  walk: 130, idle: 520, work: 300, sleep: 1400, injured: 260,
  talk: 380, fight: 110,
};

/**
 * What somebody is doing, in the order that a glance should read it.
 *
 * The caller supplies the context because most of it is not on the citizen.
 * Whether somebody is fighting depends on a raid being at the door, whether
 * they are talking depends on who is standing next to them, and whether they
 * are asleep depends on the shift and the floor — none of which a citizen
 * record knows about itself.
 *
 * THREE OF THE FIVE ANIMATIONS THIS FILE COULD NAME WERE NEVER ASKED FOR.
 * Measured over a 200-day campaign, the only actions that ever came out of
 * here were `work` and `walk`. `idle` was unreachable by construction: the old
 * `moving` argument was `!room || status !== 'working'`, so anybody without a
 * post counted as moving and every off-duty citizen in the silo was drawn
 * walking, for ever. `sleep` was gated on `status === 'resting'`, which
 * nothing in src/ ever sets, or `restShifts > 0`, which measured zero across
 * every citizen at every sample. That is 110 frames of baked art — idle,
 * sleep and injured across eleven roles — that the game could not display.
 *
 * So the contract changed: the renderer decides what somebody is doing and
 * this function only ranks it. `idle` is now what a stationary person gets,
 * which is the answer it should always have given.
 */
export function citizenAction(c, ctx = {}) {
  // A fight outranks a limp. It is the only thing that happens to the whole
  // silo at once, and a wounded defender is still a defender.
  if (ctx.fighting) return 'fight';
  if (c.health < BAL.render.injuredBelowHealth) return 'injured';
  if (ctx.sleeping) return 'sleep';
  if (onDuty(c) && !ctx.moving) return 'work';
  if (ctx.talking) return 'talk';
  if (ctx.moving) return 'walk';
  return 'idle';
}

/**
 * On duty, which is not the same as `status === 'working'`.
 *
 * Soldiers were the casualty of getting this wrong. A garrison squad's members
 * carry `status: 'training'` — they are standing watch and drilling, which is
 * their post — so a check for 'working' alone dropped every one of them
 * through to the off-shift grey. The silo's guards were drawn as civilians
 * who had knocked off, which is the opposite of what a player scanning for
 * their defence needs to see.
 *
 * `economy.js:126` already draws this line in the same place, counting both
 * statuses as somebody being at work, so this is the game's existing
 * definition rather than a new one.
 */
export function onDuty(c) {
  return c.status === 'working' || c.status === 'training';
}

/**
 * Which figure to draw them as.
 *
 * The order is the whole design, and it changed: **on shift or not** now
 * outranks age, because that is the question the cross-section is being asked.
 * Somebody at a post wears their unit's colour; everybody else wears grey
 * coveralls. Across a floor that reads instantly as "these six are running the
 * farm and those four are not", which no arrangement of silhouettes does at
 * twelve pixels.
 *
 * Condition still outranks everything: irradiated is a warning and a hazmat
 * suit means they are outside, and neither may be hidden by a job.
 *
 * Below the shift check, age still speaks — a child at school and an elder off
 * shift are both drawn as themselves, and neither is crew.
 *
 * Being on duty is the signal rather than `c.job`, and the two are not the
 * same question: `job` is the post somebody holds, on duty is whether they are
 * standing in it. Measured on a day-220 silo they agree almost exactly for
 * civilians — 34 posts, 34 working — but a citizen resting, sick or in school
 * holds their post and is not at it, and the colour should follow the body,
 * not the paperwork.
 */
export function citizenRole(c) {
  if (c.radiation >= BAL.citizens.radiation.sicknessThreshold) return 'irradiated';
  if (c.status === 'expedition') return 'hazmat';
  if (onDuty(c)) {
    if (c.squadId != null) return 'militia';
    return SKILL_ROLE[jobSkillOf(c)] || 'base';
  }
  if (c.age < BAL.citizens.workingAgeMin) return 'child';
  if (c.age >= BAL.citizens.vitality.declineSteepAge) return 'elder';
  return 'resident';
}

const SKILL_ROLE = {
  farming: 'farmer',
  mechanics: 'mechanic',
  engineering: 'mechanic',
  medicine: 'medic',
  admin: 'deputy',
  combat: 'militia',
};

/**
 * The renderer has no room table, and importing one here would pull the whole
 * data layer into the render path. The floor renderer knows the room and
 * stamps the skill onto the citizen it passes down; absent that, everyone is
 * a plain resident, which is a correct answer rather than a broken one.
 */
function jobSkillOf(c) {
  return c._jobSkill || null;
}

/**
 * A standalone canvas holding one atlas frame, for the DOM layer.
 *
 * The panels cannot draw from the atlas the way the game canvas does — they
 * are HTML — so the room interiors baked into the sheet were invisible to
 * the one screen with room to show them. This cuts a frame out
 * and hands it over as an element, nearest-neighbour at an integer zoom.
 *
 * Returns null when the atlas has not loaded or the frame does not exist, so
 * every caller keeps whatever it drew before.
 */
export function frameCanvas(name, scale = 1) {
  const f = frame(name);
  if (!f || !atlas) return null;
  const c = document.createElement('canvas');
  c.width = f.w * scale;
  c.height = f.h * scale;
  const ctx = c.getContext('2d');
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(atlas, f.x, f.y, f.w, f.h, 0, 0, c.width, c.height);
  return c;
}

/** In-world numerals, from the baked 3x5 font. UI text never goes on canvas. */
export function drawNumber(ctx, n, x, y, scale = 1) {
  const s = String(Math.max(0, Math.floor(n)));
  let cx = x;
  for (const ch of s) {
    const f = frame(`digit_${ch}`);
    if (!f) return false;
    draw(ctx, `digit_${ch}`, cx, y, f.w * scale, f.h * scale);
    cx += (f.w + 1) * scale;
  }
  return true;
}

export function numberWidth(n, scale = 1) {
  return String(Math.max(0, Math.floor(n))).length * 4 * scale;
}

export default { loadAtlas, draw, drawAt, frame, frameCanvas, citizenFrame, drawNumber, isLoaded };
