/**
 * sprites.js — atlas loader and animation state machines.
 *
 * The atlas is generated by tools/gen-atlas.mjs, so it is on-palette by
 * construction. If it fails to load the renderer falls back to the procedural
 * block shapes it used before Phase 8 — the game must never fail to draw
 * because an image 404'd.
 */

import { BAL } from '../config/balance.js';

let atlas = null;
let table = null;
let loading = null;
let failed = false;

export function isLoaded() {
  return !!atlas && !!table;
}

export function hasFailed() {
  return failed;
}

/** Load the atlas image and its frame table. Resolves either way. */
export async function loadAtlas(base = './assets/') {
  if (atlas && table) return true;
  if (loading) return loading;

  loading = (async () => {
    try {
      const [img, json] = await Promise.all([
        loadImage(base + 'atlas.png'),
        fetch(base + 'atlas.json').then((r) => r.json()),
      ]);
      atlas = img;
      table = json;
      return true;
    } catch (err) {
      console.warn('[sprites] atlas unavailable, falling back to block shapes:', err);
      failed = true;
      return false;
    }
  })();
  return loading;
}

function loadImage(src) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error('image failed: ' + src));
    img.src = src;
  });
}

export function frame(name) {
  return table?.frames?.[name] || null;
}

/**
 * Draw a frame, stretched to fit a destination box. Nearest-neighbour is
 * enforced by the caller setting imageSmoothingEnabled = false.
 */
export function draw(ctx, name, dx, dy, dw, dh) {
  if (!atlas || !table) return false;
  const f = table.frames[name];
  if (!f) return false;
  ctx.drawImage(atlas, f.x, f.y, f.w, f.h, dx, dy, dw ?? f.w, dh ?? f.h);
  return true;
}

/** Draw a frame at its natural size, top-left anchored. */
export function drawAt(ctx, name, dx, dy, scale = 1) {
  const f = frame(name);
  if (!f) return false;
  return draw(ctx, name, dx, dy, f.w * scale, f.h * scale);
}

// ------------------------------------------------------- animation state ---

/**
 * Citizen animation is derived, never stored: the frame is a pure function of
 * (id, time, state). That keeps it out of the save file and free during
 * catch-up, and it means a citizen's gait is stable across sessions.
 */
export function citizenFrame(citizen, timeMs, moving) {
  const role = citizenRole(citizen);
  const action = citizenAction(citizen, moving);
  const n = FRAME_COUNTS[action] || 1;
  // Phase by id so two people on the same floor are never in lockstep.
  const f = Math.floor(timeMs / FRAME_MS[action] + citizen.id * 3) % n;
  return `citizen_${role}_${action}${f}`;
}

/** Frames per action, matching what tools/art/citizens.mjs bakes. */
const FRAME_COUNTS = { walk: 6, idle: 4, work: 4, sleep: 2, injured: 4 };
/** How long each frame holds. Sleep breathes slowly; a walk cycle does not. */
const FRAME_MS = { walk: 130, idle: 520, work: 300, sleep: 1400, injured: 260 };

/**
 * What somebody is doing, in the order that a glance should read it.
 *
 * Injury outranks everything: a person limping is the most important thing
 * about them on screen. Sleep outranks work because a resting shift is a
 * state, not an absence of one — before this the atlas baked sleep frames
 * that nothing ever asked for.
 */
export function citizenAction(c, moving) {
  if (c.health < BAL.render.injuredBelowHealth) return 'injured';
  if (c.status === 'resting' || c.restShifts > 0) return 'sleep';
  if (moving) return 'walk';
  if (c.status === 'working') return 'work';
  return 'idle';
}

/**
 * Which figure to draw them as. Condition first — irradiated is a warning and
 * must not be hidden by a job — then age, then the work they actually do, so
 * the silo reads as a place with farmers and mechanics in it rather than two
 * hundred identical jumpsuits.
 */
export function citizenRole(c) {
  if (c.radiation >= BAL.citizens.radiation.sicknessThreshold) return 'irradiated';
  if (c.status === 'expedition') return 'hazmat';
  if (c.age < BAL.citizens.workingAgeMin) return 'child';
  if (c.age >= BAL.citizens.vitality.declineSteepAge) return 'elder';
  if (c.squadId != null) return 'militia';
  return SKILL_ROLE[jobSkillOf(c)] || 'base';
}

const SKILL_ROLE = {
  farming: 'farmer',
  mechanics: 'mechanic',
  engineering: 'mechanic',
  medicine: 'medic',
  admin: 'deputy',
  combat: 'militia',
};

/**
 * The renderer has no room table, and importing one here would pull the whole
 * data layer into the render path. The floor renderer knows the room and
 * stamps the skill onto the citizen it passes down; absent that, everyone is
 * a plain resident, which is a correct answer rather than a broken one.
 */
function jobSkillOf(c) {
  return c._jobSkill || null;
}

/**
 * A standalone canvas holding one atlas frame, for the DOM layer.
 *
 * The panels cannot draw from the atlas the way the game canvas does — they
 * are HTML — so the room interiors baked into the sheet were invisible to
 * the one screen with room to show them. This cuts a frame out
 * and hands it over as an element, nearest-neighbour at an integer zoom.
 *
 * Returns null when the atlas has not loaded or the frame does not exist, so
 * every caller keeps whatever it drew before.
 */
export function frameCanvas(name, scale = 1) {
  const f = frame(name);
  if (!f || !atlas) return null;
  const c = document.createElement('canvas');
  c.width = f.w * scale;
  c.height = f.h * scale;
  const ctx = c.getContext('2d');
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(atlas, f.x, f.y, f.w, f.h, 0, 0, c.width, c.height);
  return c;
}

/** In-world numerals, from the baked 3x5 font. UI text never goes on canvas. */
export function drawNumber(ctx, n, x, y, scale = 1) {
  const s = String(Math.max(0, Math.floor(n)));
  let cx = x;
  for (const ch of s) {
    const f = frame(`digit_${ch}`);
    if (!f) return false;
    draw(ctx, `digit_${ch}`, cx, y, f.w * scale, f.h * scale);
    cx += (f.w + 1) * scale;
  }
  return true;
}

export function numberWidth(n, scale = 1) {
  return String(Math.max(0, Math.floor(n))).length * 4 * scale;
}

export default { loadAtlas, draw, drawAt, frame, frameCanvas, citizenFrame, drawNumber, isLoaded };
